export const GET_PENDING_REQUEST = "GET_PENDING_REQUEST";
export const GET_PENDING_SUCCESS = "GET_PENDING_SUCCESS";
export const GET_PENDING_FAILURE = "GET_PENDING_FAILURE";

export const ADD_PENDING_REQUEST = "ADD_PENDING_REQUEST";
export const ADD_PENDING_SUCCESS = "ADD_PENDING_SUCCESS";
export const ADD_PENDING_FAILURE = "ADD_PENDING_FAILURE";

export const UPDATE_PENDING_REQUEST = "UPDATE_PENDING_REQUEST";
export const UPDATE_PENDING_SUCCESS = "UPDATE_PENDING_SUCCESS";
export const UPDATE_PENDING_FAILURE = "UPDATE_PENDING_FAILURE";

export const DELETE_PENDING_REQUEST = "DELETE_PENDING_REQUEST";
export const DELETE_PENDING_SUCCESS = "DELETE_PENDING_SUCCESS";
export const DELETE_PENDING_FAILURE = "DELETE_PENDING_FAILURE";

export const GET_COMPLETE_ORDER_REQUEST = "GET_COMPLETE_ORDER_REQUEST";
export const GET_COMPLETE_ORDER_SUCCESS = "GET_COMPLETE_ORDER_SUCCESS";
export const GET_COMPLETE_ORDER_FAILURE = "GET_COMPLETE_ORDER_FAILURE";

export const ADD_COMPLETE_ORDER_REQUEST = "ADD_COMPLETE_ORDER_REQUEST";
export const ADD_COMPLETE_ORDER_SUCCESS = "ADD_COMPLETE_ORDER_SUCCESS";
export const ADD_COMPLETE_ORDER_FAILURE = "ADD_COMPLETE_ORDER_FAILURE";
