export const GET_SELLERS_REQUEST = "GET_SELLERS_REQUEST";
export const GET_SELLERS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_FAILURE = "GET_SELLERS_FAILURE";

export const ADD_SELLERS_REQUEST = "ADD_SELLERS_REQUEST";
export const ADD_SELLERS_SUCCESS = "ADD_SELLERS_SUCCESS";
export const ADD_SELLERS_FAILURE = "ADD_SELLERS_FAILURE";

export const GET_BUYERS_REQUEST = "GET_BUYERS_REQUEST";
export const GET_BUYERS_SUCCESS = "GET_BUYERS_SUCCESS";
export const GET_BUYERS_FAILURE = "GET_BUYERS_FAILURE";

export const ADD_BUYERS_REQUEST = "ADD_BUYERS_REQUEST";
export const ADD_BUYERS_SUCCESS = "ADD_BUYERS_SUCCESS";
export const ADD_BUYERS_FAILURE = "ADD_BUYERS_FAILURE";


export const DELETE_SELLERS_REQUEST = "DELETE_SELLERS_REQUEST";
export const DELETE_SELLERS_SUCCESS = "DELETE_SELLERS_SUCCESS";
export const DELETE_SELLERS_FAILURE = "DELETE_SELLERS_FAILURE";

export const DELETE_BUYERS_REQUEST = "DELETE_BUYERS_REQUEST";
export const DELETE_BUYERS_SUCCESS = "DELETE_BUYERS_SUCCESS";
export const DELETE_BUYERS_FAILURE = "DELETE_BUYERS_FAILURE";
